/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiBooksBookIdFileRouteImport } from './routes/api.books.$bookId.file'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksBookIdFileRoute = ApiBooksBookIdFileRouteImport.update({
  id: '/api/books/$bookId/file',
  path: '/api/books/$bookId/file',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/upload': typeof ApiUploadRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/api/books/$bookId/file': typeof ApiBooksBookIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/upload': typeof ApiUploadRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/api/books/$bookId/file': typeof ApiBooksBookIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/upload': typeof ApiUploadRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/api/books/$bookId/file': typeof ApiBooksBookIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api/upload'
    | '/books/$bookId'
    | '/api/books/$bookId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api/upload'
    | '/books/$bookId'
    | '/api/books/$bookId/file'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/upload'
    | '/books/$bookId'
    | '/api/books/$bookId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  ApiBooksBookIdFileRoute: typeof ApiBooksBookIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId/file': {
      id: '/api/books/$bookId/file'
      path: '/api/books/$bookId/file'
      fullPath: '/api/books/$bookId/file'
      preLoaderRoute: typeof ApiBooksBookIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiUploadRoute: ApiUploadRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  ApiBooksBookIdFileRoute: ApiBooksBookIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
